FORMAT_CLASS_MAP = {
    "xl": "f-sz-xl", 
    "lg": "f-sz-lg", 
    "sm": "f-sz-sm", 
    "xs": "f-sz-xs", 

    "white": "fc-white", 
    "silver": "fc-silver", 
    "red": "fc-red", 
    "tomato": "fc-tomato", 
    "orange": "fc-orange", 
    "gold": "fc-gold", 
    "deeppink": "fc-deeppink", 
    "yellow": "fc-yellow", 
    "lime": "fc-lime", 
    "cyan": "fc-cyan", 
    "skyblue": "fc-skyblue", 
    
    "strike": "fst-strike", 
    "bold": "fst-bold", 
    "italic": "fst-italic", 

    "bg-black": "bg-black", 
    "bg-white": "bg-white", 
    "bg-darkgray": "bg-darkgray", 
    "bg-red": "bg-red", 
    "bg-tomato": "bg-tomato", 
    "bg-gold": "bg-gold", 
    "bg-blue": "bg-blue", 
    "bg-yellow": "bg-yellow", 
    "bg-orange": "bg-orange", 
    "bg-pastelpink": "bg-pastelpink", 
    "bg-pastelorange": "bg-pastelorange", 
    "bg-pastelyellow": "bg-pastelyellow", 
    "bg-pastellemon": "bg-pastellemon", 
    "bg-pastelgreen": "bg-pastelgreen", 
    "bg-pastelblue": "bg-pastelblue", 
    "bg-pastelpurple": "bg-pastelpurple", 
}